### ISSUE TITLE
[Bug]ReferenceError: __test is not defined

### ISSUE THREAD

**Issue by VictorGlindasPaf** [storybookjs/test-runner#68]
I seem to get this error seemingly at random when running the tests.
Following the stack trace just takes me to the very bottom of my story file.

```
 FAIL   browser: chromium  src/Tag.stories.tsx (26.779 s)
  ● Base Components/Tag › Variants › smoke-test

    page.evaluate: ReferenceError: __test is not defined

      at eval (eval at evaluate (:3:2389), <anonymous>:4:17)
      at t.default.evaluate (<anonymous>:3:2412)
      at t.default.<anonymous> (<anonymous>:1:44)
      at testFn (src/Tag.stories.tsx:84:37)
      at Object.<anonymous> (src/Tag.stories.tsx:99:17)
 ```

**Comment by yannbf** [comment]
Hey @VictorGlindasPaf thanks for opening this issue! Is that the only failure in your tests, or do previous tests fail too?
Is there more info you can give to help us reproduce the issue?

**Comment by VictorGlindasPaf** [comment]
These errors were definitely mixed with other ones, but I'm not sure in which order they came.

I'll see if I have time to get some more info about this when back at work on Monday.

**Comment by yannbf** [comment]
> @yannbf The error is flaky and happens occasionally. Yesterday, even in this repository, it happened once when I was running the tests. Reexecuting the tests made the error disappear. It seems to be a kind of timing issue. This happens occasionally on my private Gitlab pipeline as well (flaky). Locally it just happens rarely.

Interesting! Can we chat more about it? Can you reach out on discord at Yann#9096 or [twitter](https://twitter.com/yannbf)?

**Comment by valentinpalkovic** [comment]
@VictorGlindasPaf I had the same issue. In my case, the issue was a redirection happening in the components by using a decorator, redirecting to an SSO page when a Token was not available in the localstorage. Maybe you have a similar issue and a redirection happens in special cases or you are triggering a page reload. This would explain, why the initial script, which contains the `__test` function, is not available in the head section anymore.

**Comment by ericclemmons** [comment]
I can reproduce this by setting `resetContextPerTest: true` for https://github.com/playwright-community/jest-playwright.

**Comment by joriswitteman** [comment]
For me, this is caused when I navigate to a different URL trying to capture snapshots during `postRender()`. Probably the test runner injects something into the page that is lost by navigating to another URL.

(The use case for navigating for me, is to put different arg values in the URL and as such capture different permutations of the Story).

**Comment by gmwill934** [comment]
getting same error, following the [docs](https://storybook.js.org/docs/react/writing-tests/test-runner), it says zero config, but do we need extra config?

**Comment by AnnaHoege** [comment]
I'm also getting this error while testing web components.
It started after migrating to Storybook 7 and switching builders from webpack to vite. 

Now tests will also fail at random, probably because vite takes too long for the test-runner to render components.

**Comment by yannbf** [comment]
Hey everyone! If you can share a minimal reproduction of this issue, I'd love to take a look at.
I cannot get to reproduce this, I also tried setting `resetContextPerTest: true` as suggested by @ericclemmons.

@AnnaHoege given you have hit this issue recently, could you share a reproduction? Thank you!

**Comment by ksandin** [comment]
I can only add another anecdote that this happens randomly when using storybook 7 and vite. I get this error in the CI every now and then when making arbitrary changes, and every time it fails I can make the same build pass by simply retrying in the CI without making any code changes.

**Comment by ksandin** [comment]
I have an optimistic update: I seem to have found a consistent (but unforunately not minimal) repro. I seem to get this error consistently for .stories files that are using the play function. In the code snippet below, if I keep the `CanOnlySeeContentWhenOpen` story, I get the error. If I remove it, I do not get the error. 

> This code snippet is from a large monorepo, so it could potentially be caused by something else too, but I figured I'd share what I have.

```tsx
import { expect } from "@storybook/jest";
import type { Meta, StoryObj } from "@storybook/react";
import { userEvent, within } from "@storybook/testing-library";
import { useState } from "react";
import { Modal } from "./Modal";

export default {
  title: "atoms/Modal",
  component: Modal,
  tags: ["autodocs"],
} satisfies Meta<typeof Modal>;

export const Default: StoryObj<Meta<typeof Modal>> = {
  args: { children: "Hello World!", open: true },
};

export const CanOnlySeeContentWhenOpen: StoryObj<Meta<typeof Modal>> = {
  args: { children: "Hello World!" },
  render() {
    const [open, setOpen] = useState(false);
    return (
      <>
        <Modal open={open}>Hello World</Modal>
        <button onClick={() => setOpen(true)}>Show</button>
      </>
    );
  },
  async play({ canvasElement }) {
    const canvas = within(canvasElement);
    expect(canvas.getByText("Hello World")).not.toBeVisible();
    await userEvent.click(canvas.getByRole("button"));
    expect(canvas.getByText("Hello World")).toBeVisible();
  },
};
```

Here's my stack trace in case it helps:

```
FAIL browser: chromium src/atoms/Modal.stories.tsx (9.483 s)
    ● Console
  
      console.log
        An error occurred in the following story, most likely because of a navigation: "atoms/Modal/Default". Retrying...
  
        at Object.<anonymous> (src/atoms/Modal.stories.tsx)
  
    ● atoms/Modal › CanOnlySeeContentWhenOpen › smoke-test
  
      page.evaluate: ReferenceError: __test is not defined
  
        at eval (eval at evaluate (:202:30), <anonymous>:3:57)
        at UtilityScript.evaluate (<anonymous>:204:17)
        at UtilityScript.<anonymous> (<anonymous>:1:44)
        at src/atoms/Modal.stories.tsx:325:58
        at step (src/atoms/Modal.stories.tsx:109:23)
        at Object.next (src/atoms/Modal.stories.tsx:50:20)
        at asyncGeneratorStep (src/atoms/Modal.stories.tsx:4:28)
        at _next (src/atoms/Modal.stories.tsx:22:17)
        at src/atoms/Modal.stories.tsx:27:13
        at src/atoms/Modal.stories.tsx:19:16
        at testFn (src/atoms/Modal.stories.tsx:377:49)
        at Object.<anonymous> (src/atoms/Modal.stories.tsx:390:33)
        at step (src/atoms/Modal.stories.tsx:109:23)
        at Object.next (src/atoms/Modal.stories.tsx:50:20)
        at asyncGeneratorStep (src/atoms/Modal.stories.tsx:4:28)
        at _next (src/atoms/Modal.stories.tsx:22:17)
        at src/atoms/Modal.stories.tsx:27:13
        at Object.<anonymous> (src/atoms/Modal.stories.tsx:19:16)
```

**Comment by yannbf** [comment]
Hey @ksandin!

Given the error message:
> An error occurred in the following story, most likely because of a navigation: "atoms/Modal/Default". Retrying...

Are your stories doing any navigation on click? Navigations break the test-runner.

**Comment by ksandin** [comment]
@yannbf I have no navigations in the code that is being tested.

**Comment by matttk** [comment]
Any update on this issue? Unfortunately, we just added storybook testing to our pipeline and ran into this issue multiple times today. I can't say much about a repro, as the issue only started when to started running the tests automatically - and we haven't written many tests yet. We are using storybook version 7.5.3 and test-runner 0.14.

**Comment by yannbf** [comment]
Hey everyone, it's **really difficult** to fix an issue when there is no reproduction available. I have been trying to reproduce this but without any success of. We use the test-runner daily in about 40 different projects, and so far have not seen this error. I recall this happening in very early versions of the test-runner, but not anymore. Please do share a reproduction if you have one, I'd be incredibly thankful for that!

**Comment by ttt43ttt** [comment]
I can reproduce this when using the workaround in https://github.com/mswjs/msw-storybook-addon/issues/82
```js
// Yuck...
Loading.decorators = [
  (Story) => {
    useEffect(() => {
      return () => window.location.reload();
    }, []);

    return <Story />;
  },
];
```

**Comment by malixsys** [comment]
FYI: this happened to me when storybook was running in another terminal...

**Comment by ksandin** [comment]
Looking at the source code, this smells like a race condition to me.

The `__test` invocation is defined here:

https://github.com/storybookjs/test-runner/blob/6624c5e6b7958e05f7c9dbeb57b581e374202c2b/src/playwright/transformPlaywright.ts#L28-L30

And the `__test` definition is in `setup-page-script.ts`:
https://github.com/storybookjs/test-runner/blob/6624c5e6b7958e05f7c9dbeb57b581e374202c2b/src/setup-page-script.ts#L266

Which in turn is loaded in `setupPage`:
https://github.com/storybookjs/test-runner/blob/6624c5e6b7958e05f7c9dbeb57b581e374202c2b/src/setup-page.ts#L64-L75

Could the explanation be that there is a race between the invocation and loading of the setup page?

**Comment by throw5way** [comment]
It seems the race condition is resolved by running that initialization script not with `evaluate`, but with `runInitScript`.

```diff
diff --git a/node_modules/@storybook/test-runner/dist/playwright/transformPlaywright.js b/node_modules/@storybook/test-runner/dist/playwright/transformPlaywright.js
index f6b3bdf..328350c 100644
--- a/node_modules/@storybook/test-runner/dist/playwright/transformPlaywright.js
+++ b/node_modules/@storybook/test-runner/dist/playwright/transformPlaywright.js
@@ -57,7 +57,7 @@ const testPrefixer = (0, import_template.default)(`
           await globalThis.__sbPreRender(page, context);
         }

-        const result = await page.evaluate(({ id, hasPlayFn }) => __test(id, hasPlayFn), {
+        const result = await page.addInitScript(({ id, hasPlayFn }) => __test(id, hasPlayFn), {
           id: %%id%%,
         });

diff --git a/node_modules/@storybook/test-runner/dist/playwright/transformPlaywright.mjs b/node_modules/@storybook/test-runner/dist/playwright/transformPlaywright.mjs
index 08d0006..dfaec94 100644
--- a/node_modules/@storybook/test-runner/dist/playwright/transformPlaywright.mjs
+++ b/node_modules/@storybook/test-runner/dist/playwright/transformPlaywright.mjs
@@ -25,7 +25,7 @@ const testPrefixer = template(`
           await globalThis.__sbPreRender(page, context);
         }

-        const result = await page.evaluate(({ id, hasPlayFn }) => __test(id, hasPlayFn), {
+        const result = await page.addInitScript(({ id, hasPlayFn }) => __test(id, hasPlayFn), {
           id: %%id%%,
         });
```

**Comment by yannbf** [comment]
Hey there @throw5way thanks for the suggestion! I made a canary with the fix at #445, please try it out and give some feedback if you can. Thanks!

```
yarn add @storybook/test-runner@0.17.1--canary.445.f7d2785.0
```

**Comment by benhili** [comment]
@yannbf that fixes my issue! I have been scratching my head over this for a week.

**Comment by hans-lizihan** [comment]
for us, after upgrading the the canary version, all test pass even though they should be failing. 

also we are trying todo some individual retries to deflake test runs. 

```

**Comment by yannbf** [comment]
Hey @hans-lizihan could you please share a reproduction? I'd like to take a deeper look if possible. For the others, could you please let me know if [the canary](https://github.com/storybookjs/test-runner/issues/68#issuecomment-2020160826) solves your issues?

**Comment by blcoyote** [comment]
Hey @yannbf The canary build solves our issues as reproduced by https://github.com/storybookjs/test-runner/issues/68#issuecomment-1837872661
all the tests succeed after upgrading from 0.17.0. 
I'm awaiting the final release before upgrading our pileline though.

**Comment by yannbf** [comment]
Glad to hear that @blcoyote! It seems that it causes issues when the test-runner is used for visual regression testing though. I will have to take a deeper look into that. In the meantime, everyone else, please give the canary a try and give me feedback if possible. Thanks!

**Comment by unional** [comment]
I notice this still occurs on 0.18.1. Is the canary change included in 0.18?

And I'm running visual snapshot testing.

**Comment by yannbf** [comment]
Hey @unional it is not, it's only in that canary version so far. I need more feedback whether it introduces any issues. Is the canary working without issues for you?

**Comment by eifr** [comment]
> Hey @unional it is not, it's only in that canary version so far. I need more feedback whether it introduces any issues. Is the canary working without issues for you?

been using it for a couple of weeks and it is working with no issues for me

**Comment by chmmpagne** [comment]
@yannbf
When we tried the canary version we found all of our tests passing.
Maybe the same as @hans-lizihan above.

We have a large private repo,
but maybe I can come up with a minimal reproduction if I have some time.

**Comment by eifr** [comment]
> @yannbf When we tried the canary version we found all of our tests passing even if they should be failing. Maybe the same as @hans-lizihan above.
> 
> We have a large private repo, but maybe I can come up with a minimal reproduction if I have some time.

just tested this I'm also getting false positives :worried: 
all tests are passing although there are failing when using the ui

**Comment by Phoenixmatrix** [comment]
FYI just hit this issue. Its been tricky to repro, because it only happens for us when using Vite and the dependency optimization step has not run. Only in Storybook 8 in our case (even though it looks like this issue predates it by a fair bit). Eg, setting the vite config to have:

```
export default defineConfig({
	plugins: [react()],
	optimizeDeps: {
		force: true,
	},
});
```

Otherwise, first run fails, second run pass. But using a production build of storybook to test against bypasses this optimize dep step, so the tests always work. Not a great solution when running locally, though.

I added code in a preVisit step to wait until the setup-page-script functions are available on the global object. In the event of dep optimization, they NEVER become available (but on second run they are). It's really strange.

**Comment by ygkn** [comment]
I encountered this issue and fixed with this [patch-package](https://github.com/ds300/patch-package) file.
This is same as #445.

`patches/@storybook+test-runner+0.18.2.patch`
```patch
diff --git a/node_modules/@storybook/test-runner/dist/index.js b/node_modules/@storybook/test-runner/dist/index.js
index e1bc5a2..1aba18e 100644
--- a/node_modules/@storybook/test-runner/dist/index.js
+++ b/node_modules/@storybook/test-runner/dist/index.js
@@ -13556,7 +13556,7 @@ var testPrefixer = /* @__PURE__ */ __name((context) => {
           await globalThis.__sbPreVisit(page, context);
         }
 
-        const result = await page.evaluate(({ id, hasPlayFn }) => __test(id, hasPlayFn), {
+        const result = await page.addInitScript(({ id, hasPlayFn }) => __test(id, hasPlayFn), {
           id: %%id%%,
         });
 
diff --git a/node_modules/@storybook/test-runner/dist/index.mjs b/node_modules/@storybook/test-runner/dist/index.mjs
index c32e886..b8ca561 100644
--- a/node_modules/@storybook/test-runner/dist/index.mjs
+++ b/node_modules/@storybook/test-runner/dist/index.mjs
@@ -13539,7 +13539,7 @@ var testPrefixer = /* @__PURE__ */ __name((context) => {
           await globalThis.__sbPreVisit(page, context);
         }
 
-        const result = await page.evaluate(({ id, hasPlayFn }) => __test(id, hasPlayFn), {
+        const result = await page.addInitScript(({ id, hasPlayFn }) => __test(id, hasPlayFn), {
           id: %%id%%,
         });
 
diff --git a/node_modules/@storybook/test-runner/dist/test-storybook.js b/node_modules/@storybook/test-runner/dist/test-storybook.js
index 32bbbd8..c59380a 100755
--- a/node_modules/@storybook/test-runner/dist/test-storybook.js
+++ b/node_modules/@storybook/test-runner/dist/test-storybook.js
@@ -17621,7 +17621,7 @@ var testPrefixer = /* @__PURE__ */ __name((context) => {
           await globalThis.__sbPreVisit(page, context);
         }
 
-        const result = await page.evaluate(({ id, hasPlayFn }) => __test(id, hasPlayFn), {
+        const result = await page.addInitScript(({ id, hasPlayFn }) => __test(id, hasPlayFn), {
           id: %%id%%,
         });
 
diff --git a/node_modules/@storybook/test-runner/dist/test-storybook.mjs b/node_modules/@storybook/test-runner/dist/test-storybook.mjs
index da7fd85..0ac585b 100755
--- a/node_modules/@storybook/test-runner/dist/test-storybook.mjs
+++ b/node_modules/@storybook/test-runner/dist/test-storybook.mjs
@@ -17627,7 +17627,7 @@ var testPrefixer = /* @__PURE__ */ __name((context) => {
           await globalThis.__sbPreVisit(page, context);
         }
 
-        const result = await page.evaluate(({ id, hasPlayFn }) => __test(id, hasPlayFn), {
+        const result = await page.addInitScript(({ id, hasPlayFn }) => __test(id, hasPlayFn), {
           id: %%id%%,
         });
```

**Comment by javianpicardo** [comment]
page.evaluate: ReferenceError: __test is not defined
[TEST] 
[TEST]       at eval (eval at evaluate (:226:30)PXW.Application/, <anonymous>:3:57)
[TEST]       at UtilityScript.evaluate (PXW.Application/<anonymous>:228:17)
[TEST]       at UtilityScript.<anonymous> (PXW.Application/<anonymous>:1:44)
      at PXW.Application/src/stories/molecules/UploadFilesModal/UploadFilesModal.stories.tsx:307:58
[TEST]       at step (PXW.Application/src/stories/molecules/UploadFilesModal/UploadFilesModal.stories.tsx:109:23)
      at Object.next (PXW.Application/src/stories/molecules/UploadFilesModal/UploadFilesModal.stories.tsx:50:20)
[TEST]       at asyncGeneratorStep (PXW.Application/src/stories/molecules/UploadFilesModal/UploadFilesModal.stories.tsx:4:28)
[TEST]       at _next (PXW.Application/src/stories/molecules/UploadFilesModal/UploadFilesModal.stories.tsx:22:17)
      at PXW.Application/src/stories/molecules/UploadFilesModal/UploadFilesModal.stories.tsx:27:13
[TEST]       at PXW.Application/src/stories/molecules/UploadFilesModal/UploadFilesModal.stories.tsx:19:16
[TEST]       at testFn (PXW.Application/src/stories/molecules/UploadFilesModal/UploadFilesModal.stories.tsx:359:49)
      at Object.<anonymous> (PXW.Application/src/stories/molecules/UploadFilesModal/UploadFilesModal.stories.tsx:372:33)
[TEST]       at step (PXW.Application/src/stories/molecules/UploadFilesModal/UploadFilesModal.stories.tsx:109:23)
      at Object.next (PXW.Application/src/stories/molecules/UploadFilesModal/UploadFilesModal.stories.tsx:50:20)
[TEST]       at asyncGeneratorStep (PXW.Application/src/stories/molecules/UploadFilesModal/UploadFilesModal.stories.tsx:4:28)
[TEST]       at _next (PXW.Application/src/stories/molecules/UploadFilesModal/UploadFilesModal.stories.tsx:22:17)
      at PXW.Application/src/stories/molecules/UploadFilesModal/UploadFilesModal.stories.tsx:27:13
[TEST]       at Object.<anonymous> (PXW.Application/src/stories/molecules/UploadFilesModal/UploadFilesModal.stories.tsx:19:16)

In my msal.ts when I add the below code a group of test cases break with the above error
 // Handle redirect promise
  msalInstance
    .handleRedirectPromise()
    .then(tokenResponse => {
      if (!tokenResponse) {
        const accounts = msalInstance.getAllAccounts();
        if (accounts.length === 0) {
          msalInstance.loginRedirect();
        }
      }
    })
    .catch(err => {
      console.error('Error handling redirect:', err);
    });

**Comment by YourBassHertz** [comment]
https://github.com/storybookjs/test-runner/issues/68#issuecomment-2020160826

This solution works for me. However, not if I'm running `--coverage`. If I remove that flag, it works fine.

**Comment by javianpicardo** [comment]
I was able to solve my error. The error was in errorredirectpromise which was causing a redirect. I just had to call it before msalinstance was instance was initialized and check for any pending promises so it did not cause an redirect. Which fixed my issue.

**Comment by dfbsx** [comment]
@yannbf Hello there! The problem with __test is not defined still exist in 0.19.0 and 0.19.1 during Github Actions. I've tried to install your canary, but it provides me a lot of errors with coverage report. Files are tested correctly but for coverage report receives files like mocks or preview.js. There is a way to fix it? When I back to f.e. 0.19.0 with no canary, coverage files looks good, but I receive _test error again.

**Comment by Reclocco** [comment]
the release [0.17.1--canary.445.4041ab4.0](https://www.npmjs.com/package/@storybook/test-runner/v/0.17.1--canary.445.4041ab4.0) from [this PR](https://github.com/storybookjs/test-runner/pull/445) fixes this issue for me. It'd be nice to see this fix in main releases

**Comment by samuel-ldgfy** [comment]
Same issue here on `@storybook/test-runner@0.19.1`, using Storybook 8 & vite.
We're having an issue when running the tests in CI, the first one tends to fail due to timeout but the error in the console is the same:
```
console.log
  An error occurred in the following story, most likely because of a navigation: […]
```
For us, it only happens in the first test that runs. It does not have any navigation in the test itself.

I tried applying the patch directly from https://github.com/storybookjs/test-runner/issues/68#issuecomment-2224900181 or installing the canary version.
Both result in the pipeline passing but I tried breaking the tests on purpose and **they continue passing (as false positives)**.

**Comment by fadler82** [comment]
> @VictorGlindasPaf I had the same issue. In my case, the issue was a redirection happening in the components by using a decorator, redirecting to an SSO page when a Token was not available in the localstorage. Maybe you have a similar issue and a redirection happens in special cases or you are triggering a page reload. This would explain, why the initial script, which contains the `__test` function, is not available in the head section anymore.

@valentinpalkovic Thanks for the hint, turned out that we used a _window.location.reload_ in a decorator function which resulted in `ReferenceError: __test is not defined`

**Comment by toBeOfUse** [comment]
I can confirm that the attempted patch causes all tests to pass, even those that should fail. From a quick reading of the code, that canary version tries to make the test function run earlier, which is the opposite of what you would want; you want the setup function to run earlier, and/or the actual test to run later.

It looks to me like if you have too many stories, you will inevitably start seeing tests fail with "An error occurred in the following story, most likely because of a navigation." It looks like a lot of people who have been reporting this problem have large repos with a lot of stories. At work, where we have a lot of stories, we have been hitting this error (and some random timeouts, and occasionally the `__test is not defined` error) intermittently. It appears that you can get these problems just by having Too Many Stories.

I have a repo [here](https://github.com/toBeOfUse/large-repo-with-storybook-tests) that reliably reproduces these errors for me; it has a simple test page and 400 copies of that test page's story. In this repo, I reliably get "An error occurred in the following story, most likely because of a navigation" when running tests. (There is definitely no navigation taking place in the stories.)

This is kind of a contrived example, but like I said, I (and presumably other people in this thread) have been hitting the exact same problems in real life. In general, I don't see any real reason why there should be a limit for the number of stories the test runner should be able to support; it should be possible to run all the tests more or less in isolation, so if you can run one test, you should be able to run them all (it's not like there's any shared state between then.)

I notice that the memory and threads used by the test runner reliably increase as the test runner progresses in a large project. It seems likely to me that the underlying cause of the issue is some kind of memory leak and resource starvation is taking place; probably the execution context for the tests is being destroyed because the underlying browser is killing tabs that take too much memory, or something along those lines.

**Comment by toBeOfUse** [comment]
We are mitigating this issue by running Storybook tests in batches. We have a script that runs the storybooks whose names start with A-D, then E-M, then N-Z.

If you're using a Unix shell, you can use `find` to get the story names (example for A-D):

```bash
FILES=$(find src -type f -regex ".*\/[A-D][A-Za-z0-9_-]*\.stories\.[tj]sx$")
```

Then just run the test runner with those names after it:

```bash
npx test-storybook $FILES
```

This makes running tests and CI/CD slightly more complicated, but it eliminates the issue.

**Comment by unional** [comment]
FYI, while big project with a lot of stories are more likely to trigger it, it also happens to small project.

I have a project with < 100 stories in a monorepo, and I also run into this when I run storybook against it.

**Comment by shilman** [comment]
@vanessayuenn @yannbf seems like a good thing to fix if we can squeeze it in. WDYT?

**Comment by ext-maciej** [comment]
Any update?

**Comment by majoncas-ue** [comment]
With Storybook 8.5.0 version upgrade, I am not starting to get `An error occurred in the following story, most likely because of a navigation` issue. Is there an incoming fix?

**Comment by valentinpalkovic** [comment]
@majoncas-ue Can you provide a simple reproduction. This issue is not known

**Comment by toBeOfUse** [comment]
The problem seems to be that when you navigate to a story, the play test immediately starts running. However, in this context, you don't want it to start running until there's been time to set up the page by injecting a script and listening for the test succeeding or failing. So, the solution has been to navigate to a "blank" version of the Storybook iframe, then set up the page, and then trigger a pseudo-navigation to make the actual story show up once Playwright is ready for it. However, that pseudo-navigation occasionally has real consequences, and it wipes the page setup out.

**Comment by donaldpipowitch** [comment]
We recently started to see this issue as well randomly. And we also noticed the "_An error occurred in the following story, most likely because of a navigation_" issues that suddenly appeared (but don't make the tests fail). (See also )

Interestingly we were still on Storybook 8.4.7, so for us it was not introduced by 8.5.x. In the linked issue some thought it could be related to `@storybook/addon-a11y`, but I disabled it and the issues still appeared.
When I check our pipelines from the last days it looks like the issue started with upgrading `@storybook/test-runner` from `0.21.0` to `0.21.1`. But I had a look at the version diff and it looked pretty innocent. (I just saw `0.21.2` is out now. Will try it as well.)

**Comment by toBeOfUse** [comment]
After many sleepless nights and immolated brain cells, I have found the problem, at least as it occurs in our setup. There is a call to `window.location.reload()` in the `teardown` method of the `StoryRender` class [here](https://github.com/storybookjs/storybook/blob/212c173077015e5db2ee5da626e4ee93cb598360/code/core/src/preview-api/modules/preview-web/render/StoryRender.ts#L453). This reloads the window if the story is in [one of these phases](https://github.com/storybookjs/storybook/blob/212c173077015e5db2ee5da626e4ee93cb598360/code/core/src/preview-api/modules/preview-web/render/StoryRender.ts#L139) when the current story is being torn down and the next test needs to run. When debugging this issue, the problem seemed to be that the story was in the "afterEach" phase for too long. This reload is what destroys the Playwright execution context, and is the "navigation" mentioned in the error message.

This is the patch that fixes the problem, which can be applied with [`patch-package`](https://www.npmjs.com/package/patch-package). It waits indefinitely for the story to finish tearing down, producing a console error if it takes too long. The teardown will only be delayed for that long if there is some kind of callback returned from the `beforeEach` of a story's meta or some `experimental_afterEach` added by the user or an add-on that takes a really long time.

```patch
diff --git a/node_modules/@storybook/core/dist/preview/runtime.js b/node_modules/@storybook/core/dist/preview/runtime.js
index 0b1ef63..0662f03 100644
--- a/node_modules/@storybook/core/dist/preview/runtime.js
+++ b/node_modules/@storybook/core/dist/preview/runtime.js
@@ -6105,13 +6105,19 @@ var Sn = class Sn {
     this.abortController?.abort();
   }
   async teardown() {
     this.torndown = !0, this.cancelRender(), this.story && await this.store.cleanupStory(this.story);
-    for (let e = 0; e < 3; e += 1) {
+    let index = 0;
+    while (true) {
       if (!this.isPending()) {
         await this.teardownRender();
         return;
       }
-      await new Promise((t) => setTimeout(t, 0));
+      ++index;
+      if (index > 5) {
+        console.error("storybook teardown taking a really long time!");
+      }
+      await new Promise((t) => setTimeout(t, 10));
     }
     window.location.reload(), await new Promise(() => {
     });
```

**Comment by valentinpalkovic** [comment]
Excellent analysis! I will try to get your fix in before we release Storybook 8.6 next week.

**Comment by toBeOfUse** [comment]
@valentinpalkovic Interesting. I do not know the Storybook events well enough to completely understand the fix, but I'm guessing it delays the teardown until the afterEach functions has finished, instead of waiting on the long-running afterEach during the teardown? I can confirm that in the project I have where I previously had many navigation errors, I am seeing none with this new version (without the patch to Storybook core.)

**Comment by valentinpalkovic** [comment]
Your guess is correct! We correctly await afterEach calls before processing the next test.

**Comment by Grubsniff** [comment]
@valentinpalkovic @toBeOfUse , thank you for your discussion here, you've saved me so much time finding this. 

Do we have an update on when this will be live, if it's not already, and what version.

**Comment by valentinpalkovic** [comment]
The latest test runner 0.21.3 contains the fix!

**Comment by nick-lanners** [comment]
Hi all,
I am just starting to set up or component library project with the test-runner with Storybook v8.6.4, @storybook/test-runner v0.22.0, @storybook/react-vite v8.6.4
I am still running into this issue with the __test not being defined randomly. It happens inconsistently on firefox, on almost every test on webkit (along with some `Execution context was destroyed, most likely because of a navigation` errors), and on many tests in chromium (along with some `page.evaluate: ReferenceError: Cannot access 'StorybookTestRunnerError' before initialization`).
Firefox is the only browser that I can get any test to pass at all.
All but one of our tests, right now, are basic smoke tests.
The one `play` function that we are testing (as we get things set up) works perfectly when running in Storybook, but is inconsistent (with the above errors) in test-runner.
We are also getting a bunch of `TypeError: error loading dynamically imported module:` on all browsers, again randomly.

We were using Playwright with Storybook for component testing and it was working fine until about three weeks ago when we started having these flaky tests breaking, both on Github CI and when running locally. We have no navigation happening in any of the stories and no purposefully dynamically importing components that I can find.

I am very new to this sort of testing and build/compile configuration stuff and find myself a bit out of my depth. I'm picking this up from a more senior engineer who left our company not long ago. I'm not sure how related my issue is to this thread, but I thought it's a good place to start. I've found nothing helpful in many hours on various docs sites, stack overflow threads, and repo issues threads. Any advice or help is welcome. Thank you.

**Comment by shilman** [comment]
@nick-lanners  you might consider the new `@storybook/experimental-addon-test` since you're using Vite. https://storybook.js.org/docs/writing-tests/test-addon

**Comment by fadler82** [comment]
> The latest test runner 0.21.3 contains the fix!

As usual you hit the nail @valentinpalkovic !  Thank you very much for this fix 😺

**Comment by intermetric** [comment]
Still hitting this on 0.24.4 and 0.24.5.

#548 changed which event we wait for (`STORY_RENDERED` → `STORY_FINISHED`), but the listener never checks which story the event is actually for.

`STORY_FINISHED` gives you `{ storyId, status, reporters }`. Looks like a late event from the previous story resolves the current one, the runner moves on mid-render, the preview reloads, and `__test` is gone because it's injected with `addScriptTag`. Everything after that in the same file then fails.

Same story passes fine if it's the only one in the index, and if you reorder so a different story runs last, that one fails instead.

One line seems to fix it:
```js
// dist/setup-page-script.js
[TEST_RUNNER_RENDERED_EVENT]: (data) => {
  if (data?.storyId && data.storyId !== storyId) return;
  cleanup(listeners);
```

Should be safe for the `STORY_RENDERED` fallback too, since there the payload is just the id string, so `data?.storyId` is undefined and it behaves as before.

Tested on 735 stories (Storybook 10.5.10, playwright 1.61.1): without it I get the crash on 3/3 runs, with it 0/3, and the only remaining failure is a real axe violation. Reverting brings it straight back, on a different component the second time.

Happy to open a PR if that approach looks right to you @valentinpalkovic 🙂
